openapi: 3.0.3
info:
  title: Controle de Investimentos API
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /investments:
    get:
      summary: Listar investimentos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Investment'
    post:
      summary: Criar investimento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvestmentInput'
      responses:
        '201':
          description: Criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Investment'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /investments/{id}:
    put:
      summary: Atualizar investimento
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID do investimento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvestmentInput'
      responses:
        '200':
          description: Atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Investment'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Excluir investimento
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID do investimento
      responses:
        '204':
          description: Excluído
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /investments/types/distribution:
    get:
      summary: Distribuição por tipo de investimento
      description: Retorna a quantidade de investimentos de cada tipo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DistributionResult'

components:
  schemas:
    InvestmentInput:
      type: object
      required: [name, type, amount, investment_date]
      properties:
        name:
          type: string
        type:
          type: string
          enum: [Ações, Renda Fixa, Fundos, Criptomoedas, Imóveis, Commodities, Outros]
        amount:
          type: number
          minimum: 0.01
        investment_date:
          type: string
          format: date
    Investment:
      allOf:
        - $ref: '#/components/schemas/InvestmentInput'
        - type: object
          properties:
            id:
              type: string
            created_at:
              type: string
              format: date-time
    DistributionResult:
      type: object
      properties:
        type:
          type: string
        count:
          type: integer
    Error:
      type: object
      properties:
        error:
          type: string